name: ci

on:
  push:
    paths:
      - 'src/**'
      - 'build.gradle'
      - '.github/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.2
    - name: build
      run: ./gradlew build
    - name: publish snapshot
      if: success()
      env:
        BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
        BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
      run: ./gradlew publish -PSNAPSHOT
